site_name: João Vitor Cardoso dos Santos
site_url: https://jvcss.github.io
site_description: JVCSS Documentation
site_author: JVCSS
theme:
  name: material
  palette:
    scheme: slate  # dark mode
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.annotate
    - content.code.copy
docs_dir: doc
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Projects: README.md
  - Documentation:
      - Cv: cv.md
      - Details: HighlightAbilities.md